component: cart
app_path: /app

secrets: "{{ lookup('hashi_vault', 'secret=roboshop-{{env}}/data/cart token={{vault_token}} url=https://vault-internal.blissfulbytes.online:8200 validate_certs=false')}}"