
- name: Setup Nodejs
  ansible.builtin.include_role:
    name: common
    tasks_from: nodejs

- name: Setup App Prerequisites
  ansible.builtin.include_role:
    name: common
    tasks_from: app-prereq

#execute_as_root



