
- name: Setup Nodejs
  ansible.builtin.include_role:
    name: common
    tasks_from: nodejs

- name: Setup App Prerequisites
  ansible.builtin.include_role:
    name: common
    tasks_from: app-prereq

- name: Copy the Service file
  ansible.builtin.copy:
    src: catalogue.service
    dest: /etc/systemd/system/catalogue.service

#execute_as_root



