- name: Setup Nodejs
  ansible.builtin.include_role:
    name: common
    tasks_from: nodejs

- name: Copy the Service file
  ansible.builtin.copy:
    src: catalogue.service
    dest: /etc/systemd/system/catalogue.service

#execute_as_root



