- name: Add application User.
  ansible.builtin.user:
    name: roboshop

- name: Remove old content.
  ansible.builtin.file:
    path: "{{ app_path }}"
    state: absent

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: "{{ app_path }}"
    state: directory

- name: Download and extract Application content
  ansible.builtin.get_url:
    url: https://roboshop-artifacts.s3.amazonaws.com/{{ component }}-v3.zip
    dest: "{{ app_path }}"

