---
- name: Install Python 3
  ansible.builtin.dnf:
    name:
      - python3
      - gcc
      - python3-devel
    state: latest

- name: Setup App Prerequisites
  ansible.builtin.include_role:
    name: common
    tasks_from: app-prereq

- name: Download the Python dependencies
  ansible.builtin.shell:  pip3 install -r requirements.txt
  agrs:
    chdir: "{{ app_path }}"

- name: Load Schema
  ansible.builtin.include_role:
    name: common
    tasks_from: schema
  when: schema_setup is defined

- name: Systemd Services restarted and enabled
  ansible.builtin.include_role:
    name: common
    tasks_from: systemd

