app_path: /app
schema_setup: mongo
component: catalogue
schema_files:
  - master-data


secrets: "{{ lookup('hashi_vault', 'secret=roboshop-{{env}}/data/catalogue token={{vault_token}} url=https://vault-internal.blissfulbytes.online:8200 validate_certs=false')}}"
